# Copyright (C) 2010, 2011, 2012  Olga Yakovleva <yakovleva.o.v@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import os.path

Import(["env","libcore"])
local_env=env.Clone()
local_env["liblevel"]=2
local_env.Prepend(LIBS=["comsuppw","advapi32","shell32"])
local_env.Prepend(LIBS=local_env["libcore"])

dll_name="RHVoiceSvr"
dll_src=["com.cpp",
         "ISpDataKeyImpl.cpp",
         "IEnumSpObjectTokensImpl.cpp",
         "ISpTTSEngineImpl.cpp",
         "main.cpp",
         "registry.cpp",
         "SpeakImpl.cpp",
         "ArabicTextProcessor.cpp",
         "ArabicNum2Words.cpp",
         "tts_base.cpp",
         "voice_token.cpp",
         "dll.def"]

import urllib.request
import zipfile
import os

arch = local_env.get("TARGET_ARCH", "x86")
if arch == "x86_64":
    onnx_name = "onnxruntime-win-x64-1.17.1"
else:
    onnx_name = "onnxruntime-win-x86-1.17.1"

onnx_dir = local_env.Dir("#external/" + onnx_name).abspath
if not os.path.exists(onnx_dir):
    url = f"https://github.com/microsoft/onnxruntime/releases/download/v1.17.1/{onnx_name}.zip"
    zip_path = os.path.join(local_env.Dir("#external").abspath, f"{onnx_name}.zip")
    urllib.request.urlretrieve(url, zip_path)
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(local_env.Dir("#external").abspath)

local_env.Append(CPPPATH=[f'#external/{onnx_name}/include'])
local_env.Append(LIBPATH=[f'#external/{onnx_name}/lib'])

# Note: we need to link onnxruntime if it's there
local_env.Prepend(LIBS=["onnxruntime"])

lib=local_env.BuildLibrary(dll_name,dll_src)
local_env.Depends(lib,libcore)
